# Generated by Django 3.1.7 on 2021-04-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('log', models.TextField()),
                ('finished_file', models.FilePathField(path='/jobs')),
            ],
        ),
    ]
