# Generated by Django 3.1.7 on 2021-05-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='schema',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
